[[redirects]]
from = "/properties"
to = "/properties.html"
status = 200

[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/login"
to = "/login.html"
status = 200

[[redirects]]
from = "/profile"
to = "/profile.html"
status = 200

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 404

[build]
command = "npx vite build"
publish = "dist"